# Generated by Django 6.0.3 on 2026-04-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dfa',
            field=models.BooleanField(default=True),
        ),
    ]
