# Generated by Django 6.0.3 on 2026-04-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_dfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
