# Generated by Django 6.0.3 on 2026-04-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famille',
            name='user',
        ),
    ]
