# Generated by Django 6.0.3 on 2026-04-21 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_famille_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='montant',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='date_incineration_prevue',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='defunt',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='motif',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='moyen_paiement',
        ),
        migrations.CreateModel(
            name='LignePaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motif', models.CharField(default='Inhumation', max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_inhumation', models.DateTimeField()),
                ('date_incineration', models.DateField()),
                ('moyen_paiement', models.CharField(max_length=50)),
                ('defunt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_paiement', to='api.defunt')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.paiement')),
            ],
            options={
                'verbose_name': 'Ligne de paiement',
                'verbose_name_plural': 'Lignes de paiement',
            },
        ),
    ]
