# Generated by Django 6.0.3 on 2026-04-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_montant_paiement_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignepaiement',
            name='date_incineration',
        ),
        migrations.RemoveField(
            model_name='lignepaiement',
            name='date_inhumation',
        ),
    ]
