import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Syne } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      data-theme="halloween"
      className={`${syne.variable} h-full antialiased`}
    >
      <body style={{ fontFamily: 'var(--font-syne)' }}>{children}</body>
      {/* <body>{children}</body> */}
    </html>
  );
}
